### ISSUE TITLE
bitcoin rpc query and setup btc test infra

### ISSUE THREAD

**Issue by lesterli** [babylonchain/babylon-finality-gadget#41]
## Summary

https://github.com/babylonchain/babylon-da-sdk/pull/39#pullrequestreview-2155202342
> Gai: Just wanted to understand the context. Why not use btc client like https://github.com/babylonchain/staking-indexer/blob/51d98f1dbafda2fbbe550599c83331b549d26a6c/btcclient/client.go#L23?

https://github.com/babylonchain/finality-provider/pull/483#discussion_r1667869280
> Runchao: besides mocking BTC node, one can also leverage the https://github.com/btcsuite/btcd/tree/master/integration/rpctest package for testing things against an almost real BTC node. But this can be done in the future.

## Tasks

- [x] refactor bitcoin rpc query using [this](https://github.com/babylonchain/staking-indexer/blob/dev/btcclient/client.go#L17) 
- [ ] rewrite btc tests to not depend on ankr RPC
- [ ] decide whether we should leverage the [rpctest](https://github.com/btcsuite/btcd/tree/master/integration/rpctest) or [bitcoind](https://github.com/babylonchain/staking-indexer/blob/dev/itest/bitcoind_node_setup.go) package for testing things against an almost real BTC node. finalise the design with the Babylon team
- [ ] rewrite the tests using the btc test infra
- [ ] add more btcclient tests for some edge cases

**Comment by parketh** [comment]
now updated Bitcoin rpc to use `btcclient` with [this](https://github.com/babylonchain/babylon-da-sdk/pull/39/commits/ec5dcf968c1ee244adeaab7e7fd64ce84c87cbde) commit

task 2 is still standing

**Comment by bap2pecs** [comment]
closing as 2 is now tracked in https://github.com/babylonchain/babylon-finality-gadget/issues/49

**Comment by bap2pecs** [comment]
Kamino closed and cloned this issue to [babylonlabs-io/babylon-finality-gadget](https://github.com/babylonlabs-io/babylon-finality-gadget/issues/3)
