### ISSUE TITLE
Refactor: decouple config, sdk, and client

### ISSUE THREAD

**Issue by bap2pecs** [babylonchain/babylon-finality-gadget#43]
## context

https://github.com/babylonchain/babylon-da-sdk/pull/38#pullrequestreview-2155195317
> LGTM! In general, I think we can start to refactor the project a bit in terms of architecture in subsequent prs. For example, config is now mixed with client. Many structs are mixed with sdk along with client methods

https://github.com/babylonchain/babylon-da-sdk/pull/45#discussion_r1666279613
> Suggest we formalise the mock procedure for unit tests, like what we did in finality provider

## tasks

- [x] https://github.com/babylonchain/babylon-finality-gadget/pull/55
- [x] https://github.com/babylonchain/babylon-finality-gadget/pull/56
- [x] get rid of test dependency on stub cw contract

**Comment by bap2pecs** [comment]
let's also rewrite all tests to not depend on anything external. so we will decouple from:

- BTC mainnet RPC
- Stub contract deployed on Sei

right now `make test` and `make run` are both broken. but since we are already covering this SDK in the e2e test in FP repo, I suggest we only do mocked unit test here

cc @lesterli @parketh wdyt?

**Comment by bap2pecs** [comment]
example: https://github.com/babylonchain/babylon-da-sdk/pull/45

**Comment by bap2pecs** [comment]
https://github.com/babylonchain/babylon-da-sdk/pull/45#discussion_r1666279613

**Comment by bap2pecs** [comment]
https://github.com/babylonchain/finality-provider/pull/483#discussion_r1667869280

> besides mocking BTC node, one can also leverage the https://github.com/btcsuite/btcd/tree/master/integration/rpctest package for testing things against an almost real BTC node. But this can be done in the future.

**Comment by bap2pecs** [comment]
closing as we are tracking ^ work items in https://github.com/babylonchain/babylon-finality-gadget/issues/49
