### ISSUE TITLE
Refactor: Streamline the APIs and tests

### ISSUE THREAD

**Issue by bap2pecs** [babylonchain/babylon-finality-gadget#49]
## Summary

We want to refactor the project architecture. For example, `config` is now mixed with `client`. Many structs are mixed with `sdk` along with client methods. We also want to clean up the tests to either automatically handle mock generation and/or use a local BTC devnet.

## Tasks

- [ ] decouple multiple packages per this [comment](https://github.com/babylonchain/babylon-finality-gadget/pull/38#pullrequestreview-2155195317)
- [ ] get rid of stub CW contract in tests
- [ ] remove the `/demo` folder and `make` command
- [ ] rewrite btc tests to not depend on ankr RPC. we should leverage the [rpctest](https://github.com/btcsuite/btcd/tree/master/integration/rpctest) package for testing things against an almost real BTC node 
- [ ] avoid using `zap.NewProduction()` in test
- [ ] (optional - might not need it if we use `rpctest`) formalise the mock procedure for unit tests, like what we did in finality provider
- [ ] fix incorrect comment "TestBtc is an e2e test to call into a stub CosmWasm contract deployed on Osmosis testnet"
