### ISSUE TITLE
ensure the changes here will not break FP e2e tests

### ISSUE THREAD

**Issue by bap2pecs** [babylonchain/babylon-finality-gadget#52]
## Summary

We want to ensure that changes here will still work with the FP repo, but the problem is that the e2e tests are in the FP repository.

We are currently getting the commit hash in this repo and locally updated it in the cloned FP repository. Then we run e2e tests manually in the FP repo

But imagine having to do this every time we make a PR in this repo—it's tedious. So, a proposed solution is to rely on the CI in this repo.

how it works should be first we clone the FP repository and get the commit hash of the PR here. then replace the dependency in the FP repository and run `go mod tidy`, and then run e2e tests

## Tasks

- [ ] create CI job to clone FP repo, fetch commit hash of the current PR
- [ ] replace the deps in the FP repo and run `go mod tidy`
- [ ] run FP e2e tests

**Comment by bap2pecs** [comment]
Kamino closed and cloned this issue to [babylonlabs-io/babylon-finality-gadget](https://github.com/babylonlabs-io/babylon-finality-gadget/issues/2)
