### ISSUE TITLE
Refactor: move CosmWasm contract to this repo

### ISSUE THREAD

**Issue by bap2pecs** [babylonchain/babylon-finality-gadget#7]
## Summary

https://github.com/babylonchain/babylon-da-sdk/issues/2#issuecomment-2179567693

## Tasks

- [ ] figure out how to import code from one repo to another
- [ ] figure out how to set up CI
- [ ] update binary in FP's `bytecode` folder

**Comment by bap2pecs** [comment]
https://github.com/babylonchain/babylon-finality-gadget/issues/49

**Comment by bap2pecs** [comment]
Kamino closed and cloned this issue to [babylonlabs-io/babylon-finality-gadget](https://github.com/babylonlabs-io/babylon-finality-gadget/issues/6)
